[tool.autopep8]
max_line_length = 89
aggressive = 3
[tool.isort]
line_length = 89
[tool.ruff]
line-length=89

select = ["A", # flake8-builtins
"ARG", # flake8-unused-arguments
"B", # flake8-bugbear
"C4", # flake8-comprehensions
"D", # Docstringstyle
"E", # pycodestyle errors
"EM", # flake8-errmsg
"F", # pyflakes
"I", # isort
"INP", # flake8-INP
"ISC", # flake8-implicit-str-concat
"N", # pep8-naming
"PIE", # flake8-pie
"PL", # pylint
"PT", # flake8-pytest-style
"Q", # flake8-quotes
"RET", # flake8-return
"RSE", # flake8-raise
"SIM", # flake8-simplify
"T20", # flake8-print
"W"] # pycodestyle warnings
ignore = ["D100", 
"N999", 
"PLR0913", 
"PLR0915", 
"PLR2004",
"D407"]

# Allow autofix for all selected rules when `--fix` is provided.
fixable = [
           "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", 
           "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", 
           "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", 
           "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
[tool.ruff.flake8-quotes]
inline-quotes = "single"

# Ignore unused imports error in __init__.py files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
