# Specify base image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy current direc into the container
COPY . .

# Install packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run command
CMD [ "python" , "perform_benchmarking.py"]
